version: "3"
services:
  datascience-notebook:
      image: jupyter/datascience-notebook
      volumes:
        - /home/antonio/Documentos/github/PythonFundamentos:/home/jovyan/work
      ports:
        - 8888:8888
      container_name:   datascience-notebook-container