version: '3.1'

services:
  db-postgres: 
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
    volumes:
      - /home/antonio/Documentos/github/docker/environment/composer/pg/data:/var/lib/postgresql/data 
    ports: 
      - 5432:5432
    networks:
      - postgres-compose-network    
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "antonioggca000@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "16543:80"
    depends_on:
      - db-postgres
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge
